[project]
name = "deltavison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python",
    "numpy",
    "matplotlib",
    "torch",
    "fastapi",
    "uvicorn[standard]",
    "scikit-image",
    "streamlit",
]
